name: emr-fault-analyzer
services:
  postgres:
    image: pgvector/pgvector:pg17-trixie
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=emr_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/data
  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=neo4j/mypassword
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  pgdata:
  qdrant_data:
  neo4j_data:
